id: I3224C336
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:42:27+00:00'
last_modified: '2022-06-09T15:18:46.826701+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2KG210295
  title: བཀའ་འགྱུར། ༼ཕུག་བྲག་བྲིས་མ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4DFE:
      image_group_id: I2KG210405
      title: ''
      total_pages: 0
      order: 1
      base_file: 4DFE.txt
    '2470':
      image_group_id: I2KG210406
      title: ''
      total_pages: 0
      order: 2
      base_file: 2470.txt
    9F98:
      image_group_id: I2KG210407
      title: ''
      total_pages: 0
      order: 3
      base_file: 9F98.txt
    474F:
      image_group_id: I2KG210408
      title: ''
      total_pages: 0
      order: 4
      base_file: 474F.txt
    5D64:
      image_group_id: I2KG210409
      title: ''
      total_pages: 0
      order: 5
      base_file: 5D64.txt
    B52B:
      image_group_id: I2KG210410
      title: ''
      total_pages: 0
      order: 6
      base_file: B52B.txt
    2EC0:
      image_group_id: I2KG210411
      title: ''
      total_pages: 0
      order: 7
      base_file: 2EC0.txt
    '7474':
      image_group_id: I2KG210412
      title: ''
      total_pages: 0
      order: 8
      base_file: 7474.txt
    88CD:
      image_group_id: I2KG210425
      title: ''
      total_pages: 0
      order: 21
      base_file: 88CD.txt
    09B6:
      image_group_id: I2KG210414
      title: ''
      total_pages: 0
      order: 10
      base_file: 09B6.txt
    2E39:
      image_group_id: I2KG210415
      title: ''
      total_pages: 0
      order: 11
      base_file: 2E39.txt
    '5755':
      image_group_id: I2KG210416
      title: ''
      total_pages: 0
      order: 12
      base_file: 5755.txt
    F0F4:
      image_group_id: I2KG210417
      title: ''
      total_pages: 0
      order: 13
      base_file: F0F4.txt
    '5792':
      image_group_id: I2KG210418
      title: ''
      total_pages: 0
      order: 14
      base_file: 5792.txt
    89F4:
      image_group_id: I2KG210419
      title: ''
      total_pages: 0
      order: 15
      base_file: 89F4.txt
    4EC3:
      image_group_id: I2KG210420
      title: ''
      total_pages: 0
      order: 16
      base_file: 4EC3.txt
    6F6C:
      image_group_id: I2KG210421
      title: ''
      total_pages: 0
      order: 17
      base_file: 6F6C.txt
    F9AE:
      image_group_id: I2KG210422
      title: ''
      total_pages: 0
      order: 18
      base_file: F9AE.txt
    4D24:
      image_group_id: I2KG210423
      title: ''
      total_pages: 0
      order: 19
      base_file: 4D24.txt
    77BD:
      image_group_id: I2KG210424
      title: ''
      total_pages: 0
      order: 20
      base_file: 77BD.txt
    F14E:
      image_group_id: I2KG210426
      title: ''
      total_pages: 0
      order: 22
      base_file: F14E.txt
    '8733':
      image_group_id: I2KG210427
      title: ''
      total_pages: 0
      order: 23
      base_file: 8733.txt
    F2FD:
      image_group_id: I2KG210428
      title: ''
      total_pages: 0
      order: 24
      base_file: F2FD.txt
    '8398':
      image_group_id: I2KG210429
      title: ''
      total_pages: 0
      order: 25
      base_file: 8398.txt
    AF41:
      image_group_id: I2KG210430
      title: ''
      total_pages: 0
      order: 26
      base_file: AF41.txt
    '9585':
      image_group_id: I2KG210431
      title: ''
      total_pages: 0
      order: 27
      base_file: 9585.txt
    17C0:
      image_group_id: I2KG210432
      title: ''
      total_pages: 0
      order: 28
      base_file: 17C0.txt
    '4718':
      image_group_id: I2KG210433
      title: ''
      total_pages: 0
      order: 29
      base_file: 4718.txt
    '6847':
      image_group_id: I2KG210434
      title: ''
      total_pages: 0
      order: 30
      base_file: 6847.txt
    9DAB:
      image_group_id: I2KG210435
      title: ''
      total_pages: 0
      order: 31
      base_file: 9DAB.txt
    78B9:
      image_group_id: I2KG210436
      title: ''
      total_pages: 0
      order: 32
      base_file: 78B9.txt
    78F7:
      image_group_id: I2KG210437
      title: ''
      total_pages: 0
      order: 33
      base_file: 78F7.txt
    AC27:
      image_group_id: I2KG210438
      title: ''
      total_pages: 0
      order: 34
      base_file: AC27.txt
    604D:
      image_group_id: I2KG210439
      title: ''
      total_pages: 0
      order: 35
      base_file: 604D.txt
    A0D6:
      image_group_id: I2KG210440
      title: ''
      total_pages: 0
      order: 36
      base_file: A0D6.txt
    '6600':
      image_group_id: I2KG210441
      title: ''
      total_pages: 0
      order: 37
      base_file: 6600.txt
    FA76:
      image_group_id: I2KG210442
      title: ''
      total_pages: 0
      order: 38
      base_file: FA76.txt
    '3711':
      image_group_id: I2KG210443
      title: ''
      total_pages: 0
      order: 39
      base_file: 3711.txt
    22E9:
      image_group_id: I2KG210444
      title: ''
      total_pages: 0
      order: 40
      base_file: 22E9.txt
    CD41:
      image_group_id: I2KG210445
      title: ''
      total_pages: 0
      order: 41
      base_file: CD41.txt
    492F:
      image_group_id: I2KG210446
      title: ''
      total_pages: 0
      order: 42
      base_file: 492F.txt
    C747:
      image_group_id: I2KG210447
      title: ''
      total_pages: 0
      order: 43
      base_file: C747.txt
    F5CE:
      image_group_id: I2KG210448
      title: ''
      total_pages: 0
      order: 44
      base_file: F5CE.txt
    E361:
      image_group_id: I2KG210449
      title: ''
      total_pages: 0
      order: 45
      base_file: E361.txt
    F6B6:
      image_group_id: I2KG210450
      title: ''
      total_pages: 0
      order: 46
      base_file: F6B6.txt
    A3BA:
      image_group_id: I2KG210451
      title: ''
      total_pages: 0
      order: 47
      base_file: A3BA.txt
    6AA6:
      image_group_id: I2KG210452
      title: ''
      total_pages: 0
      order: 48
      base_file: 6AA6.txt
    2B3C:
      image_group_id: I2KG210453
      title: ''
      total_pages: 0
      order: 49
      base_file: 2B3C.txt
    '1636':
      image_group_id: I2KG210454
      title: ''
      total_pages: 0
      order: 50
      base_file: 1636.txt
    B6A6:
      image_group_id: I2KG210455
      title: ''
      total_pages: 0
      order: 51
      base_file: B6A6.txt
    '4111':
      image_group_id: I2KG210456
      title: ''
      total_pages: 0
      order: 52
      base_file: 4111.txt
    99BF:
      image_group_id: I2KG210457
      title: ''
      total_pages: 0
      order: 53
      base_file: 99BF.txt
    866F:
      image_group_id: I2KG210458
      title: ''
      total_pages: 0
      order: 54
      base_file: 866F.txt
    C9C7:
      image_group_id: I2KG210459
      title: ''
      total_pages: 0
      order: 55
      base_file: C9C7.txt
    36D9:
      image_group_id: I2KG210460
      title: ''
      total_pages: 0
      order: 56
      base_file: 36D9.txt
    A52F:
      image_group_id: I2KG210461
      title: ''
      total_pages: 0
      order: 57
      base_file: A52F.txt
    74D3:
      image_group_id: I2KG210462
      title: ''
      total_pages: 0
      order: 58
      base_file: 74D3.txt
    CF43:
      image_group_id: I2KG210463
      title: ''
      total_pages: 0
      order: 59
      base_file: CF43.txt
    '9161':
      image_group_id: I2KG210464
      title: ''
      total_pages: 0
      order: 60
      base_file: 9161.txt
    686F:
      image_group_id: I2KG210465
      title: ''
      total_pages: 0
      order: 61
      base_file: 686F.txt
    E1DF:
      image_group_id: I2KG210466
      title: ''
      total_pages: 0
      order: 62
      base_file: E1DF.txt
    2EC4:
      image_group_id: I2KG210467
      title: ''
      total_pages: 0
      order: 63
      base_file: 2EC4.txt
    59B8:
      image_group_id: I2KG210468
      title: ''
      total_pages: 0
      order: 64
      base_file: 59B8.txt
    860B:
      image_group_id: I2KG210469
      title: ''
      total_pages: 0
      order: 65
      base_file: 860B.txt
    BDA6:
      image_group_id: I2KG210470
      title: ''
      total_pages: 0
      order: 66
      base_file: BDA6.txt
    4EF8:
      image_group_id: I2KG210471
      title: ''
      total_pages: 0
      order: 67
      base_file: 4EF8.txt
    8C9A:
      image_group_id: I2KG210472
      title: ''
      total_pages: 0
      order: 68
      base_file: 8C9A.txt
    332F:
      image_group_id: I2KG210473
      title: ''
      total_pages: 0
      order: 69
      base_file: 332F.txt
    B147:
      image_group_id: I2KG210474
      title: ''
      total_pages: 0
      order: 70
      base_file: B147.txt
    9C84:
      image_group_id: I2KG210475
      title: ''
      total_pages: 0
      order: 71
      base_file: 9C84.txt
    CD90:
      image_group_id: I2KG210476
      title: ''
      total_pages: 0
      order: 72
      base_file: CD90.txt
    0FEC:
      image_group_id: I2KG210477
      title: ''
      total_pages: 0
      order: 73
      base_file: 0FEC.txt
    FCAC:
      image_group_id: I2KG210478
      title: ''
      total_pages: 0
      order: 74
      base_file: FCAC.txt
    6AD7:
      image_group_id: I2KG210479
      title: ''
      total_pages: 0
      order: 75
      base_file: 6AD7.txt
    1F4C:
      image_group_id: I2KG210480
      title: ''
      total_pages: 0
      order: 76
      base_file: 1F4C.txt
    A7C6:
      image_group_id: I2KG210481
      title: ''
      total_pages: 0
      order: 77
      base_file: A7C6.txt
    1AE6:
      image_group_id: I2KG210482
      title: ''
      total_pages: 0
      order: 78
      base_file: 1AE6.txt
    C375:
      image_group_id: I2KG210483
      title: ''
      total_pages: 0
      order: 79
      base_file: C375.txt
    '4444':
      image_group_id: I2KG210484
      title: ''
      total_pages: 0
      order: 80
      base_file: 4444.txt
    '4177':
      image_group_id: I2KG210485
      title: ''
      total_pages: 0
      order: 81
      base_file: 4177.txt
    C442:
      image_group_id: I2KG210486
      title: ''
      total_pages: 0
      order: 82
      base_file: C442.txt
    90F1:
      image_group_id: I2KG210487
      title: ''
      total_pages: 0
      order: 83
      base_file: 90F1.txt
    C89E:
      image_group_id: I2KG210488
      title: ''
      total_pages: 0
      order: 84
      base_file: C89E.txt
    C8B7:
      image_group_id: I2KG210489
      title: ''
      total_pages: 0
      order: 85
      base_file: C8B7.txt
    895D:
      image_group_id: I2KG210490
      title: ''
      total_pages: 0
      order: 86
      base_file: 895D.txt
    EB35:
      image_group_id: I2KG210491
      title: ''
      total_pages: 0
      order: 87
      base_file: EB35.txt
    FF84:
      image_group_id: I2KG210492
      title: ''
      total_pages: 0
      order: 88
      base_file: FF84.txt
    ADEA:
      image_group_id: I2KG210493
      title: ''
      total_pages: 0
      order: 89
      base_file: ADEA.txt
    '4366':
      image_group_id: I2KG210494
      title: ''
      total_pages: 0
      order: 90
      base_file: 4366.txt
    '2992':
      image_group_id: I2KG210495
      title: ''
      total_pages: 0
      order: 91
      base_file: 2992.txt
    C4E8:
      image_group_id: I2KG210496
      title: ''
      total_pages: 0
      order: 92
      base_file: C4E8.txt
    7D25:
      image_group_id: I2KG210497
      title: ''
      total_pages: 0
      order: 93
      base_file: 7D25.txt
    38C5:
      image_group_id: I2KG210498
      title: ''
      total_pages: 0
      order: 94
      base_file: 38C5.txt
    9E2E:
      image_group_id: I2KG210499
      title: ''
      total_pages: 0
      order: 95
      base_file: 9E2E.txt
    D054:
      image_group_id: I2KG210500
      title: ''
      total_pages: 0
      order: 96
      base_file: D054.txt
    A8AA:
      image_group_id: I2KG210501
      title: ''
      total_pages: 0
      order: 97
      base_file: A8AA.txt
    B53D:
      image_group_id: I2KG210502
      title: ''
      total_pages: 0
      order: 98
      base_file: B53D.txt
    B591:
      image_group_id: I2KG210503
      title: ''
      total_pages: 0
      order: 99
      base_file: B591.txt
    '5976':
      image_group_id: I2KG210504
      title: ''
      total_pages: 0
      order: 100
      base_file: 5976.txt
    DC58:
      image_group_id: I2KG210505
      title: ''
      total_pages: 0
      order: 101
      base_file: DC58.txt
    BAFA:
      image_group_id: I2KG210506
      title: ''
      total_pages: 0
      order: 102
      base_file: BAFA.txt
    80B8:
      image_group_id: I2KG210507
      title: ''
      total_pages: 0
      order: 103
      base_file: 80B8.txt
    75C4:
      image_group_id: I2KG210508
      title: ''
      total_pages: 0
      order: 104
      base_file: 75C4.txt
    F3A2:
      image_group_id: I2KG210509
      title: ''
      total_pages: 0
      order: 105
      base_file: F3A2.txt
    E934:
      image_group_id: I2KG210510
      title: ''
      total_pages: 0
      order: 106
      base_file: E934.txt
    732B:
      image_group_id: I2KG210511
      title: ''
      total_pages: 0
      order: 107
      base_file: 732B.txt
    4D3A:
      image_group_id: I2KG210512
      title: ''
      total_pages: 0
      order: 108
      base_file: 4D3A.txt
    793D:
      image_group_id: I2KG210513
      title: ''
      total_pages: 0
      order: 109
      base_file: 793D.txt
    EB6C:
      image_group_id: I2KG210514
      title: ''
      total_pages: 0
      order: 110
      base_file: EB6C.txt
    94E2:
      image_group_id: I2KG210515
      title: ''
      total_pages: 0
      order: 111
      base_file: 94E2.txt
    '2938':
      image_group_id: I2KG210516
      title: ''
      total_pages: 0
      order: 112
      base_file: 2938.txt
    3DC8:
      image_group_id: I2KG210517
      title: ''
      total_pages: 0
      order: 113
      base_file: 3DC8.txt
    0093:
      image_group_id: I2KG210518
      title: ''
      total_pages: 0
      order: 114
      base_file: 0093.txt
    B6D3:
      image_group_id: I2KG210519
      title: ''
      total_pages: 0
      order: 115
      base_file: B6D3.txt
    A292:
      image_group_id: I2KG210520
      title: ''
      total_pages: 0
      order: 116
      base_file: A292.txt
    570E:
      image_group_id: I2KG210521
      title: ''
      total_pages: 0
      order: 117
      base_file: 570E.txt
    902A:
      image_group_id: I2KG210522
      title: ''
      total_pages: 0
      order: 118
      base_file: 902A.txt
    '5405':
      image_group_id: I2KG210523
      title: ''
      total_pages: 0
      order: 119
      base_file: 5405.txt
    '1606':
      image_group_id: I2KG210524
      title: ''
      total_pages: 0
      order: 120
      base_file: 1606.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
